"""Interactive setup that writes non-secret config.yaml and optional secrets.env."""

from __future__ import annotations

import argparse
import getpass
import os
import tempfile
from collections.abc import Callable, Mapping
from pathlib import Path

import yaml

from .config import is_secret_name

Input = Callable[[str], str]
Output = Callable[[str], None]
SecretInput = Callable[[str], str]


def _prompt_choice(
    prompt: str,
    choices: Mapping[str, str],
    *,
    default: str,
    input_fn: Input,
    output_fn: Output,
) -> str:
    display = "/".join(f"{key}{'*' if key == default else ''}" for key in choices)
    while True:
        value = input_fn(f"{prompt} [{display}]: ").strip().lower() or default
        if value in choices:
            return value
        output_fn(f"Please choose one of: {', '.join(choices)}.")


def _prompt_text(prompt: str, *, default: str, input_fn: Input) -> str:
    return input_fn(f"{prompt} [{default}]: ").strip() or default


def _prompt_required_secret(
    prompt: str, *, secret_input: SecretInput, output_fn: Output
) -> str:
    while True:
        value = secret_input(f"{prompt} (input hidden): ")
        if value:
            return value
        output_fn(
            "This value is required for the selected feature. Press Ctrl-C to stop instead."
        )


def _quote_env_value(value: str) -> str:
    if value and all(char.isalnum() or char in "_./:@?&=+,-" for char in value):
        return value
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_env_file(
    values: Mapping[str, str], comments: list[str] | None = None
) -> str:
    """Render secret environment values; retained as a small, testable helper."""
    lines = [
        "# Generated by study-agent-setup. Keep this file private; it contains secrets."
    ]
    lines.extend(f"# {comment}" for comment in comments or [])
    lines.append("")
    lines.extend(f"{name}={_quote_env_value(value)}" for name, value in values.items())
    return "\n".join(lines) + "\n"


def _config_document(values: Mapping[str, str], run_style: str) -> dict[str, object]:
    mcp_url = values.get("STUDY_AGENT_MCP_URL", "http://127.0.0.1:8790/mcp")
    if run_style == "docker":
        mcp_url = "http://mcp-server:8790/mcp"
    document: dict[str, object] = {
        "version": 1,
        "profile": run_style,
        "paths": {
            "phenotype_index": values.get("PHENOTYPE_INDEX_DIR", "data/phenotype_index")
        },
        "network": {"rewrite_container_hosts": run_style == "docker"},
        "acp": {
            "bind": {
                "host": values["STUDY_AGENT_HOST"],
                "port": int(values["STUDY_AGENT_PORT"]),
            },
            "mcp": {
                "mode": "stdio" if "STUDY_AGENT_MCP_COMMAND" in values else "http",
                "timeout_seconds": 240,
            },
        },
        "mcp": {
            "transport": values.get("MCP_TRANSPORT", "http"),
            "bind": {
                "host": values.get("MCP_HOST", "127.0.0.1"),
                "port": int(values.get("MCP_PORT", "8790")),
            },
            "path": values.get("MCP_PATH", "/mcp"),
        },
    }
    acp = document["acp"]
    assert isinstance(acp, dict)
    mcp = acp["mcp"]
    assert isinstance(mcp, dict)
    if mcp["mode"] == "http":
        mcp["url"] = mcp_url
    else:
        mcp["command"] = values["STUDY_AGENT_MCP_COMMAND"]
    if "LLM_API_URL" in values:
        document["llm"] = {
            "api_url": values["LLM_API_URL"],
            "model": values["LLM_MODEL"],
            "use_responses_api": values.get("LLM_USE_RESPONSES", "0") == "1",
        }
    if "EMBED_URL" in values:
        document["retrieval"] = {
            "embedding_url": values["EMBED_URL"],
            "embedding_model": values["EMBED_MODEL"],
        }
    if "VOCAB_SEARCH_PROVIDER" in values:
        document["keeper"] = {
            "vocabulary": {
                "search_provider": values["VOCAB_SEARCH_PROVIDER"],
                "search_url": values["VOCAB_SEARCH_URL"],
            },
            "phoebe": {
                "provider": values["PHOEBE_PROVIDER"],
                "bulk_url": values["PHOEBE_BULK_URL"],
            },
        }
    return document


def render_config_file(values: Mapping[str, str], run_style: str) -> str:
    document = _config_document(values, run_style)
    return (
        "# Generated by study-agent-setup. This file must not contain secrets.\n"
        + yaml.safe_dump(document, sort_keys=False)
    )


def collect_configuration(
    *,
    input_fn: Input = input,
    output_fn: Output = print,
    secret_input: SecretInput = getpass.getpass,
) -> tuple[dict[str, str], dict[str, str], str]:
    """Collect ordinary settings and secrets separately."""
    output_fn(
        "Study Agent setup writes config.yaml plus an optional secret-only secrets.env."
    )
    run_style = _prompt_choice(
        "How will you run the services?",
        {"native": "direct Python commands", "docker": "Docker Compose"},
        default="native",
        input_fn=input_fn,
        output_fn=output_fn,
    )
    values = {
        "STUDY_AGENT_HOST": _prompt_text(
            "ACP host",
            default="127.0.0.1" if run_style == "native" else "0.0.0.0",
            input_fn=input_fn,
        ),
        "STUDY_AGENT_PORT": _prompt_text("ACP port", default="8765", input_fn=input_fn),
    }
    if run_style == "native":
        connection = _prompt_choice(
            "How should ACP connect to MCP?",
            {"http": "separate HTTP MCP server", "stdio": "managed MCP subprocess"},
            default="http",
            input_fn=input_fn,
            output_fn=output_fn,
        )
        if connection == "stdio":
            values["STUDY_AGENT_MCP_COMMAND"] = _prompt_text(
                "MCP command", default="study-agent-mcp", input_fn=input_fn
            )
        else:
            host = _prompt_text("MCP host", default="127.0.0.1", input_fn=input_fn)
            port = _prompt_text("MCP port", default="8790", input_fn=input_fn)
            path = _prompt_text("MCP HTTP path", default="/mcp", input_fn=input_fn)
            path = path if path.startswith("/") else f"/{path}"
            values.update(
                {
                    "MCP_TRANSPORT": "http",
                    "MCP_HOST": host,
                    "MCP_PORT": port,
                    "MCP_PATH": path,
                    "STUDY_AGENT_MCP_URL": f"http://{host}:{port}{path}",
                }
            )
    else:
        values.update(
            {
                "MCP_TRANSPORT": "http",
                "MCP_HOST": "0.0.0.0",
                "MCP_PORT": "8790",
                "MCP_PATH": "/mcp",
                "STUDY_AGENT_MCP_URL": "http://mcp-server:8790/mcp",
            }
        )
    secrets: dict[str, str] = {}
    if (
        _prompt_choice(
            "Configure LLM-backed flows?",
            {"yes": "yes", "no": "no"},
            default="yes",
            input_fn=input_fn,
            output_fn=output_fn,
        )
        == "yes"
    ):
        values["LLM_API_URL"] = _prompt_text(
            "OpenAI-compatible LLM API URL",
            default=(
                "http://host.docker.internal:3000/api/chat/completions"
                if run_style == "docker"
                else "http://localhost:3000/api/chat/completions"
            ),
            input_fn=input_fn,
        )
        values["LLM_MODEL"] = _prompt_text(
            "LLM model", default="agentstudyassistant", input_fn=input_fn
        )
        secrets["LLM_API_KEY"] = _prompt_required_secret(
            "LLM API key", secret_input=secret_input, output_fn=output_fn
        )
        values["LLM_USE_RESPONSES"] = (
            "1"
            if _prompt_choice(
                "Does this provider use the Responses API?",
                {"yes": "yes", "no": "no"},
                default="no",
                input_fn=input_fn,
                output_fn=output_fn,
            )
            == "yes"
            else "0"
        )
    if (
        _prompt_choice(
            "Configure phenotype retrieval?",
            {"yes": "yes", "no": "no"},
            default="yes",
            input_fn=input_fn,
            output_fn=output_fn,
        )
        == "yes"
    ):
        values["PHENOTYPE_INDEX_DIR"] = (
            "/data/phenotype_index"
            if run_style == "docker"
            else _prompt_text(
                "Path to the built phenotype index",
                default=str((Path.cwd() / "data" / "phenotype_index").resolve()),
                input_fn=input_fn,
            )
        )
        values["EMBED_URL"] = _prompt_text(
            "Embedding API URL",
            default=(
                "http://host.docker.internal:3000/ollama/api/embed"
                if run_style == "docker"
                else "http://localhost:3000/ollama/api/embed"
            ),
            input_fn=input_fn,
        )
        values["EMBED_MODEL"] = _prompt_text(
            "Embedding model", default="qwen3-embedding:4b", input_fn=input_fn
        )
        if (
            _prompt_choice(
                "Does the embedding API require a key?",
                {"yes": "yes", "no": "no"},
                default="no",
                input_fn=input_fn,
                output_fn=output_fn,
            )
            == "yes"
        ):
            secrets["EMBED_API_KEY"] = _prompt_required_secret(
                "Embedding API key", secret_input=secret_input, output_fn=output_fn
            )
    keeper = _prompt_choice(
        "Configure optional Keeper vocabulary support?",
        {"none": "not now", "hecate": "Hecate HTTP", "omop": "OMOP database"},
        default="none",
        input_fn=input_fn,
        output_fn=output_fn,
    )
    if keeper == "hecate":
        values.update(
            {
                "VOCAB_SEARCH_PROVIDER": "hecate_api",
                "VOCAB_SEARCH_URL": "https://hecate.pantheon-hds.com/api/search_standard",
                "PHOEBE_PROVIDER": "hecate_api",
                "PHOEBE_BULK_URL": "https://hecate.pantheon-hds.com/api/concepts/phoebe/bulk",
            }
        )
    elif keeper == "omop":
        secrets["OMOP_DB_ENGINE"] = _prompt_required_secret(
            "OMOP SQLAlchemy database URL",
            secret_input=secret_input,
            output_fn=output_fn,
        )
        values.update(
            {
                "VOCAB_METADATA_PROVIDER": "db",
                "VOCAB_DATABASE_SCHEMA": _prompt_text(
                    "Vocabulary database schema",
                    default="vocabulary",
                    input_fn=input_fn,
                ),
            }
        )
    return values, secrets, run_style


def write_env_file(
    path: Path,
    content: str,
    *,
    overwrite: bool = False,
    mode: int = 0o600,
) -> None:
    """Atomically create a file without printing its contents."""
    path = path.expanduser()
    if path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent, text=True
    )
    try:
        if hasattr(os, "fchmod"):
            os.fchmod(descriptor, mode)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temporary_name, path)
        try:
            os.chmod(path, mode)
        except OSError:
            pass  # Windows does not implement POSIX file modes in the same way.
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def _read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip().strip("\"'")
    return values


def migrate_env(path: Path) -> tuple[dict[str, str], dict[str, str], str]:
    values = _read_env(path)
    secrets = {key: value for key, value in values.items() if is_secret_name(key)}
    ordinary = {key: value for key, value in values.items() if key not in secrets}
    run_style = "docker" if ordinary.get("MCP_HOST") == "0.0.0.0" else "native"
    return ordinary, secrets, run_style


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Interactively create Study Agent config.yaml and optional secrets.env files."
    )
    parser.add_argument(
        "--config-output",
        type=Path,
        default=Path("config.yaml"),
        help="Non-secret YAML destination (default: config.yaml).",
    )
    parser.add_argument(
        "--secrets-output",
        type=Path,
        default=Path("secrets.env"),
        help="Secret environment destination (default: secrets.env).",
    )
    parser.add_argument(
        "--migrate-env",
        type=Path,
        help="Classify an existing .env file without displaying its values.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace existing destination files without prompting.",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    targets = [args.config_output, args.secrets_output]
    if any(target.exists() for target in targets) and not args.force:
        if input(
            "A configuration output file already exists. Replace it? [y/N]: "
        ).strip().lower() not in {"y", "yes"}:
            print("No changes made.")
            return
    values, secrets, run_style = (
        migrate_env(args.migrate_env) if args.migrate_env else collect_configuration()
    )
    write_env_file(
        args.config_output,
        render_config_file(values, run_style),
        overwrite=args.force or args.config_output.exists(),
        mode=0o644,
    )
    if secrets:
        write_env_file(
            args.secrets_output,
            render_env_file(secrets),
            overwrite=args.force or args.secrets_output.exists(),
        )
    print(
        f"Wrote {args.config_output}. No secret values were placed in YAML or displayed."
    )
    if secrets:
        print("Wrote secrets environment file with hidden secret values.")
    print(
        "Next: Docker Compose reads config.yaml and secrets.env. Native services use --config config.yaml."
    )


if __name__ == "__main__":
    main()
