"""Interactive, additive setup help for a local Study Agent checkout.

The wizard deliberately writes configuration only. It does not load ``.env``
files or alter the startup behavior of the ACP or MCP services.
"""

from __future__ import annotations

import argparse
import getpass
import os
import re
import tempfile
from collections.abc import Callable, Mapping
from pathlib import Path

Input = Callable[[str], str]
Output = Callable[[str], None]
SecretInput = Callable[[str], str]
_SAFE_ENV_VALUE = re.compile(r"^[A-Za-z0-9_./:@?&=+,-]+$")


def _prompt_choice(
    prompt: str,
    choices: Mapping[str, str],
    *,
    default: str,
    input_fn: Input,
    output_fn: Output,
) -> str:
    display = "/".join(f"{key}{'*' if key == default else ''}" for key in choices)
    while True:
        value = input_fn(f"{prompt} [{display}]: ").strip().lower() or default
        if value in choices:
            return value
        output_fn(f"Please choose one of: {', '.join(choices)}.")


def _prompt_text(prompt: str, *, default: str, input_fn: Input) -> str:
    return input_fn(f"{prompt} [{default}]: ").strip() or default


def _prompt_required_secret(
    prompt: str, *, secret_input: SecretInput, output_fn: Output
) -> str:
    while True:
        value = secret_input(f"{prompt} (input hidden): ")
        if value:
            return value
        output_fn(
            "This value is required for the selected feature. Press Ctrl-C to stop instead."
        )


def _quote_env_value(value: str) -> str:
    """Return a conservative dotenv/Compose-compatible serialized value."""
    if value and _SAFE_ENV_VALUE.fullmatch(value):
        return value
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_env_file(
    values: Mapping[str, str], comments: list[str] | None = None
) -> str:
    """Render values without exposing them through the wizard's normal output."""
    lines = [
        "# Generated by study-agent-setup. Keep this file private; it may contain secrets."
    ]
    lines.extend(f"# {comment}" for comment in comments or [])
    lines.append("")
    lines.extend(f"{name}={_quote_env_value(value)}" for name, value in values.items())
    return "\n".join(lines) + "\n"


def collect_configuration(
    *,
    input_fn: Input = input,
    output_fn: Output = print,
    secret_input: SecretInput = getpass.getpass,
) -> tuple[dict[str, str], list[str], str]:
    """Collect a minimal configuration for the user's selected feature profile."""
    output_fn("Study Agent setup writes a .env file for one local checkout.")
    output_fn(
        "Only choose features you plan to use now; advanced settings remain optional."
    )
    run_style = _prompt_choice(
        "How will you run the services?",
        {"direct": "direct Python commands", "docker": "Docker Compose"},
        default="direct",
        input_fn=input_fn,
        output_fn=output_fn,
    )
    values: dict[str, str] = {
        "STUDY_AGENT_HOST": _prompt_text(
            "ACP host", default="127.0.0.1", input_fn=input_fn
        ),
        "STUDY_AGENT_PORT": _prompt_text("ACP port", default="8765", input_fn=input_fn),
    }
    comments: list[str] = []

    if run_style == "docker":
        values.update(
            {
                "MCP_TRANSPORT": "http",
                "MCP_HOST": "127.0.0.1",
                "MCP_PORT": "8790",
                "MCP_PATH": "/mcp",
                "STUDY_AGENT_MCP_URL": "http://127.0.0.1:8790/mcp",
            }
        )
        comments.append(
            "Docker Compose supplies ACP's internal MCP URL when it starts the services."
        )
    else:
        connection = _prompt_choice(
            "How should ACP connect to MCP?",
            {"http": "separate HTTP MCP server", "stdio": "managed MCP subprocess"},
            default="http",
            input_fn=input_fn,
            output_fn=output_fn,
        )
        if connection == "http":
            mcp_host = _prompt_text("MCP host", default="127.0.0.1", input_fn=input_fn)
            mcp_port = _prompt_text("MCP port", default="8790", input_fn=input_fn)
            mcp_path = _prompt_text("MCP HTTP path", default="/mcp", input_fn=input_fn)
            if not mcp_path.startswith("/"):
                mcp_path = f"/{mcp_path}"
            values.update(
                {
                    "MCP_TRANSPORT": "http",
                    "MCP_HOST": mcp_host,
                    "MCP_PORT": mcp_port,
                    "MCP_PATH": mcp_path,
                    "STUDY_AGENT_MCP_URL": f"http://{mcp_host}:{mcp_port}{mcp_path}",
                }
            )
        else:
            values["STUDY_AGENT_MCP_COMMAND"] = _prompt_text(
                "MCP command", default="study-agent-mcp", input_fn=input_fn
            )

    if (
        _prompt_choice(
            "Configure LLM-backed flows?",
            {"yes": "yes", "no": "no"},
            default="yes",
            input_fn=input_fn,
            output_fn=output_fn,
        )
        == "yes"
    ):
        values["LLM_API_URL"] = _prompt_text(
            "OpenAI-compatible LLM API URL",
            default="http://localhost:3000/api/chat/completions",
            input_fn=input_fn,
        )
        values["LLM_MODEL"] = _prompt_text(
            "LLM model", default="agentstudyassistant", input_fn=input_fn
        )
        values["LLM_API_KEY"] = _prompt_required_secret(
            "LLM API key", secret_input=secret_input, output_fn=output_fn
        )
        values["LLM_USE_RESPONSES"] = (
            "1"
            if _prompt_choice(
                "Does this provider use the Responses API?",
                {"yes": "yes", "no": "no"},
                default="no",
                input_fn=input_fn,
                output_fn=output_fn,
            )
            == "yes"
            else "0"
        )

    if (
        _prompt_choice(
            "Configure phenotype retrieval?",
            {"yes": "yes", "no": "no"},
            default="yes",
            input_fn=input_fn,
            output_fn=output_fn,
        )
        == "yes"
    ):
        if run_style == "docker":
            values["PHENOTYPE_INDEX_DIR"] = "/data/phenotype_index"
            comments.append(
                "Docker Compose mounts ./data/phenotype_index from the host at /data/phenotype_index."
            )
        else:
            values["PHENOTYPE_INDEX_DIR"] = _prompt_text(
                "Absolute path to the built phenotype index",
                default=str((Path.cwd() / "data" / "phenotype_index").resolve()),
                input_fn=input_fn,
            )
        values["EMBED_URL"] = _prompt_text(
            "Embedding API URL",
            default="http://localhost:3000/ollama/api/embed",
            input_fn=input_fn,
        )
        values["EMBED_MODEL"] = _prompt_text(
            "Embedding model", default="qwen3-embedding:4b", input_fn=input_fn
        )
        if (
            _prompt_choice(
                "Does the embedding API require a key?",
                {"yes": "yes", "no": "no"},
                default="no",
                input_fn=input_fn,
                output_fn=output_fn,
            )
            == "yes"
        ):
            values["EMBED_API_KEY"] = _prompt_required_secret(
                "Embedding API key", secret_input=secret_input, output_fn=output_fn
            )

    keeper = _prompt_choice(
        "Configure optional Keeper vocabulary support?",
        {"none": "not now", "hecate": "Hecate HTTP", "omop": "OMOP database"},
        default="none",
        input_fn=input_fn,
        output_fn=output_fn,
    )
    if keeper == "hecate":
        values.update(
            {
                "VOCAB_SEARCH_PROVIDER": "hecate_api",
                "VOCAB_SEARCH_URL": "https://hecate.pantheon-hds.com/api/search_standard",
                "PHOEBE_PROVIDER": "hecate_api",
                "PHOEBE_BULK_URL": "https://hecate.pantheon-hds.com/api/concepts/phoebe/bulk",
            }
        )
    elif keeper == "omop":
        values["OMOP_DB_ENGINE"] = _prompt_required_secret(
            "OMOP SQLAlchemy database URL",
            secret_input=secret_input,
            output_fn=output_fn,
        )
        values["VOCAB_METADATA_PROVIDER"] = "db"
        values["VOCAB_DATABASE_SCHEMA"] = _prompt_text(
            "Vocabulary database schema", default="vocabulary", input_fn=input_fn
        )
    return values, comments, run_style


def write_env_file(path: Path, content: str, *, overwrite: bool = False) -> None:
    """Atomically create a private env file without exposing its contents."""
    path = path.expanduser()
    if path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent, text=True
    )
    try:
        if hasattr(os, "fchmod"):
            os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temporary_name, path)
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass  # Windows does not implement POSIX file modes in the same way.
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Interactively create a minimal Study Agent .env file."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(".env"),
        help="Destination file (default: .env).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing destination without prompting.",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    output_path = args.output.expanduser()
    if output_path.exists() and not args.force:
        answer = (
            input(f"{output_path} already exists. Replace it? [y/N]: ").strip().lower()
        )
        if answer not in {"y", "yes"}:
            print("No changes made.")
            return
    values, comments, run_style = collect_configuration()
    write_env_file(
        output_path,
        render_env_file(values, comments),
        overwrite=args.force or output_path.exists(),
    )
    print(f"Wrote {output_path}. Secret values were not displayed.")
    if run_style == "docker":
        print(
            "Next: run docker compose up --build, then check http://127.0.0.1:8765/health."
        )
    else:
        print(
            "This additive first version does not load .env for direct service commands automatically."
        )
        print(
            "Use the generated values in your shell, or run with Docker Compose. Automatic loading is planned separately."
        )


if __name__ == "__main__":
    main()
